spring:
  r2dbc:
    url: r2dbc:h2:file:///./db/authdb
    username: sa
    password:
  flyway:
    enabled: true
    url: jdbc:h2:file:./db/authdb
    user: ${spring.r2dbc.username}
    password: ${spring.r2dbc.password}
    baseline-on-migrate: true

jwt:
  secretKey: 594001a0-412f-4752-8b18-3f89f7bc5e3b


logging:
  level:
    io.r2dbc: INFO
    one.adri.auth_server: DEBUG
